misitio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ori.urls')),
]


#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
] + static ( settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

"""
urlpatterns += [
    static ( settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
]"""

"""
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$' , serve, {
        'document_root' : settings.MEDIA_ROOT,
    })
]
"""
handler404= 'ori.views.error_404'

ori/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #Área user normal
    path('', views.portada, name="portada"),
    path('dashboard/', views.dashboard, name="dashboard"),

    path('proyectos/', views.proyectos, name="proyectos"),
    path('ver_proyecto/<int:pk>', views.ver_proyecto, name="ver_proyecto"),

    path('participantes/', views.participantes, name="participantes"),
    path('ver_participante/<int:pk>', views.ver_participante, name="ver_participante"),

    path('timesheet/', views.timesheet, name="timesheet"),
    path('ver_timesheet/<int:pk>', views.ver_timesheet, name="ver_timesheet"),

    path('convocatorias/', views.convocatorias, name="convocatorias"),
    path('ver_convocatoria/<int:pk>', views.ver_convocatoria, name="ver_convocatoria"),

    path('programas/', views.programas, name="programas"),
    path('ver_programa/<int:pk>', views.ver_programa, name="ver_programa"),

    path('subprogramas/', views.subprogramas, name="subprogramas"),
    path('ver_subprograma/<int:pk>', views.ver_subprograma, name="ver_subprograma"),
    
    path('ver_perfil/', views.ver_perfil, name="ver_perfil"),
    path('editar_perfil/', views.editar_perfil, name="editar_perfil"),
    path('eliminar_perfil/', views.eliminar_perfil, name="eliminar_perfil"),

    #Área Staff
    path('nuevo_proyecto/', views.nuevo_proyecto, name="nuevo_proyecto"),
    path('editar_proyecto/<int:pk>', views.editar_proyecto, name="editar_proyecto"),
    path('borrar_proyecto/<int:pk>', views.borrar_proyecto, name="borrar_proyecto"),

    path('nuevo_participante/', views.nuevo_participante, name="nuevo_participante"),
    path('editar_participante/<int:pk>', views.editar_participante, name="editar_participante"),
    path('borrar_participante/<int:pk>', views.borrar_participante, name="borrar_participante"),

    path('nueva_timesheet/', views.nueva_timesheet, name="nueva_timesheet"),
    path('editar_timesheet/<int:pk>', views.editar_timesheet, name="editar_timesheet"),
    path('borrar_timesheet/<int:pk>', views.borrar_timesheet, name="borrar_timesheet"),

    path('nuevo_programa/', views.nuevo_programa, name="nuevo_programa"),
    path('editar_programa/<int:pk>', views.editar_programa, name="editar_programa"),
    path('borrar_programa/<int:pk>', views.borrar_programa, name="borrar_programa"),

    path('nuevo_subprograma/', views.nuevo_subprograma, name="nuevo_subprograma"),
    path('editar_subprograma/<int:pk>', views.editar_subprograma, name="editar_subprograma"),
    path('borrar_subprograma/<int:pk>', views.borrar_subprograma, name="borrar_subprograma"),

    path('nueva_convocatoria/', views.nueva_convocatoria, name="nueva_convocatoria"),
    path('editar_convocatoria/<int:pk>', views.editar_convocatoria, name="editar_convocatoria"),
    path('borrar_convocatoria/<int:pk>', views.borrar_convocatoria, name="borrar_convocatoria"),

    path('borrar_archivo/<int:pk>', views.borrar_archivo, name="borrar_archivo"),
    path('borrar_tarea/<int:pk>', views.borrar_tarea, name="borrar_tarea"),

    #Área del Admin 

    #EXTRA
    path('información/', views.informacion, name="informacion"),
    path('contacto/', views.contacto, name="contacto"),
]

ori/models.py
import os

from django.contrib.auth.models import AbstractUser
from django.db import models

#https://www.youtube.com/watch?v=QBzsoQPgJQ8&t=198s
#https://www.youtube.com/watch?v=eIG0xq00p5A

class Periodicidad(models.Model):
    #id = models.BigAutoField(primary_key=True)
    tipo_periodicidad = models.CharField(max_length=40, unique=True)
    periodosanuales = models.IntegerField(unique=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'periodicidad'

    def __str__(self):
        return self.tipo_periodicidad

class PartnershipAgreement(models.Model):
    #id = models.BigAutoField(primary_key=True)
    estado = models.CharField(max_length=100, unique=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'partnership_agreement'

    def __str__(self):
        return self.estado

class Institucion(models.Model):
    #id = models.BigAutoField(primary_key=True)
    nombreinstitucion = models.CharField(max_length=200, unique=True)
    email = models.EmailField(max_length=200, null=True)
    pais = models.CharField(max_length=200, null=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)
    
    class Meta:
        db_table = 'institucion'

    def __str__(self):
        return self.nombreinstitucion

class Proyecto(models.Model):
    proyecto_id = models.AutoField(primary_key=True)
    nombreproyecto = models.CharField(max_length=200)
    sigla = models.CharField(max_length=10, blank=True, null=True)
    id_referencia = models.IntegerField(blank=True, null=True)
    web = models.CharField(max_length=100, blank=True, null=True)
    notas = models.CharField(max_length=500, blank=True, null=True)
    coordina_institucion = models.ForeignKey(Institucion, on_delete=models.CASCADE)
    partnership_agreement = models.ForeignKey(PartnershipAgreement, on_delete=models.CASCADE, blank=True, null=True)
    periodicidad = models.ForeignKey(Periodicidad, on_delete=models.CASCADE)
    fecha_fin = models.DateField()
    fecha_inicio = models.DateField()
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)
    
    class Meta:
        db_table = 'proyecto'

    def __str__(self):
        return self.nombreproyecto

class File(models.Model):
    #id = models.BigAutoField(primary_key=True)
    file = models.FileField(upload_to="archivos/",null=False, blank=False,)
    file_proyecto_id = models.OneToOneField(Proyecto, on_delete=models.CASCADE,null=False, blank=False)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'file'

    def __str__(self):
        return self.file

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.file.path):
            os.remove(self.file.path)
        super(File, self).delete(*args, **kwargs)

class Presupuesto(models.Model):
    #id = models.BigAutoField(primary_key=True)
    proyecto = models.OneToOneField(Proyecto, on_delete=models.CASCADE)
    organismo_financiador = models.CharField(max_length=100)
    total = models.CharField(max_length=100)
    presentacion = models.DateField(auto_now = False,auto_now_add=False, null=True, blank=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'presupuesto'

class Departamento(models.Model):
    #id = models.BigAutoField(primary_key=True)
    nombredepartamento = models.CharField(max_length=200, unique=True)
    correo = models.EmailField(max_length=200, null=True, blank=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'departamento'

    def __str__(self):
        return self.nombredepartamento

class Participante(AbstractUser):
    username = models.CharField(max_length=200, unique=True)
    vinculacion = models.CharField(max_length=200, null=True, blank=True)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(max_length=200, unique=True)
    notas = models.CharField(max_length=200, null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'participante'

    def __str__(self):
        return self.username

class Rol(models.Model):
    #id = models.BigAutoField(primary_key=True)
    rolename = models.CharField(max_length=200, unique=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'rol'

    def __str__(self):
        return self.rolename

class Periodo(models.Model):
    #id = models.BigAutoField(primary_key=True)
    num_periodo = models.IntegerField()
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'periodo'
        unique_together = ('id','proyecto')

    def __str__(self):
        return str(self.num_periodo)

class Timesheet(models.Model):
    #id = models.BigAutoField(primary_key=True)
    #nombretimesheet = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE)
    periodo = models.ForeignKey(Periodo, on_delete=models.CASCADE)
    intellectual_output = models.CharField(max_length=200,null=True, blank=True)
    num_working_days = models.IntegerField(null=True, blank=True)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'timesheet'
        unique_together = ('rol', 'periodo')

    def __str__(self):
        return str(self.id)

class Tarea(models.Model):
    #id = models.BigAutoField(primary_key=True)
    nombretarea = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)
    dia = models.DateField()
    lugar = models.CharField(max_length=200)
    timesheet = models.ForeignKey(Timesheet, on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'tarea'

    def __str__(self):
        return self.nombretarea

class Programa(models.Model):
    #id = models.BigAutoField(primary_key=True)
    nombreprograma = models.CharField(max_length=200)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'programa'

    def __str__(self):
        return self.nombreprograma

class Subprograma(models.Model):
    #id = models.BigAutoField(primary_key=True)
    nombresubprograma = models.CharField(max_length=200, unique=True)
    programa = models.ForeignKey(Programa, on_delete=models.CASCADE,related_name='programapadre')
    padresubprograma = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True,related_name='subprogramahijo')
    padreprograma = models.ForeignKey(Programa, on_delete=models.CASCADE, blank=True, null=True,related_name='programahijo') 
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'subprograma'
        unique_together = ('id','programa')

    def __str__(self):
        return self.nombresubprograma

class Convocatoria(models.Model):
    #id = models.BigAutoField(primary_key=True)
    anio = models.IntegerField()
    #tiempo = models.CharField(max_length=200)
    #anio = models.DateField()
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)    

    class Meta:
        db_table = 'convocatoria'

    def __str__(self):
        return str(self.anio)

class ConvocatoriaConvocatoriasSubprogramas(models.Model):
    #id = models.BigAutoField(primary_key=True)
    convocatoria = models.ForeignKey(Convocatoria, on_delete=models.CASCADE)
    subprograma = models.ForeignKey('Subprograma', on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'convocatoria_convocatorias_subprogramas'
        unique_together = ('convocatoria', 'subprograma')
    
    def __str__(self):
        return "Convocatoria: " + str(self.convocatoria) + " y subprograma: " + str(self.subprograma)

class ParticipanteProyectos(models.Model):
    #id = models.BigAutoField(primary_key=True)
    participante = models.ForeignKey(Participante, on_delete=models.CASCADE)
    proyecto = models.ForeignKey('Proyecto', on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'participante_proyectos'
        unique_together = ('participante', 'proyecto')

    def __str__(self):
        return "Participante: " + str(self.participante) + " y proyecto: " + str(self.proyecto)

class ProyectoParticipaInstitucion(models.Model):
    #id = models.BigAutoField(primary_key=True)
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    institucion = models.ForeignKey(Institucion, on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now = False,auto_now_add=True, null=True)

    class Meta:
        db_table = 'proyecto_participa_institucion'
        unique_together = (('proyecto', 'institucion'),)

    def __str__(self):
        return "Proyecto: " + str(self.proyecto) + " y institución: " + str(self.institucion)

class Posee(models.Model):
    #id = models.BigAutoField(primary_key=True)

ori/templates/editar_convocatoria.html
{% extends "base.html" %}
{% block tittle %}
Ori | Editar convocatoria {{convocatoria.anio}}
{% endblock %}

{% block active_module_convocatoria%}
active
{% endblock %}

{% block open_convocatoria%}-open{% endblock %}

{% block active_convocatorias %}
active
{% endblock %}

{% block titulo_main %}
Editar convocatoria <b>{{convocatoria.anio}}</b>
{% endblock %}

{% block path_main %}
<li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
<li class="breadcrumb-item active">editar_convocatoria/{{convocatoria.id}}</li>
{% endblock %}

{% block main %}
<section class="content">
    
    <div class="row">
        <div class="col-md-6">
            <div class="card card-olive">
                <div class="card-header">
                    <h3 class="card-title">Edición de la convocatoria <b>{{convocatoria.anio}}</b></h3>                   
                </div>
                <div class="card-body">
                    <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                        {% csrf_token %}    

                        <div class="form-group">
                            {{form.anio.label_tag}}
                            {{form.anio}}
                            {{form.errors.anio}}
                        </div>

                        <hr class="mb-2">
                        <div class="col">          
                            <input name="convocatoriaform" type="submit" value="Editar convocatoria" class="btn btn-success float-right">
                        </div>
                    </form>
                </div>

            </div>
            
        </div>
        <div class="col-md-6">
            <div class="card card-gray">
                <div class="card-header">
                    <h3 class="card-title">Subprogramas añadidos</h3>
                </div>
                <div class="card-body">
                    <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            {{form1.subprograma.label_tag}}
                            {{form1.subprograma}}
                            {{form1.errors.subprograma}}
                        </div>
  

                        <div class="form-group">
                            {{form1.convocatoria.label_tag}}
                            <select name="convocatoria" class="form-control" required="" id="id_convocatoria" readonly>
                                
                                <option selected value={{convocatoria.id}}>{{convocatoria.anio}}</option>
                            </select>
                            {{form1.errors.convocatoria}}
                        </div>


                        <hr class="mb-2">
                        <div class="col">
                            <a href="{% url 'convocatorias' %}" class="btn btn-secondary">Cancel</a>
                            <input name="subprogramaenconvocatoriaform" type="submit" value="Añadir subprograma" class="btn btn-success float-right">
                        </div>
                    </form>

                    <hr class="mb-2">
                    {% if subprogramasListados %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Subprograma</th>
                                <th>Programa</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for subprogramasListado in subprogramasListados %}
                            <tr>
                                <td>{{subprogramasListado.nombresubprograma}}</td>
                                <td>{{subprogramasListado.programa}}</td>

                                <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <td class="text-right py-0 align-middle">
                                        <div class="btn-group btn-group-sm">
                                            <a title="Ver subprograma" href="/ver_subprograma/{{subprogramasListado.id}}"
                                                class="btn btn-info"><i class="fas fa-eye"></i>
                                            </a>
                                            
                                            <input hidden type="text" name="id_subprogramaconvocatoria"
                                                value={{subprogramasListado.id}} class="form-control"
                                                id="id_subprogramaconvocatoria">

                                            <input title="Eliminar subprograma de la convocatoria" name="eliminasubprogramaconvocatoriaform" type="submit" value="Eliminar del proyecto" class="btn btn-danger">
                                            
                                        </div>
                                    </td>
                                </form>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}

                </div>

            </div>

            
        </div>
    </div>
</section>
{% endblock %}

ori/templates/editar_programa.html
{% extends "base.html" %}
{% block tittle %}
Ori | Editar programa {{programa.id}}
{% endblock %}

{% block active_module_programa%}
active
{% endblock %}

{% block open_programa%}-open{% endblock %}

{% block active_programas %}
active
{% endblock %}

{% block titulo_main %}
Editar programa <b>{{programa.nombreprograma}}</b>
{% endblock %}

{% block path_main %}
<li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
<li class="breadcrumb-item active">editar_programa/{{programa.id}}</li>
{% endblock %}

{% block main %}
<section class="content">
    
    <div class="row">
        <div class="col-md-6">
            <div class="card card-gray-dark">
                <div class="card-header">
                    <h3 class="card-title">Edición del programa {{programa.nombreprograma}}</h3>
                </div>
                <div class="card-body">
                    <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                        {% csrf_token %}    

                        <div class="form-group">
                            {{form.nombreprograma.label_tag}}
                            {{form.nombreprograma}}
                            {{form.errors.nombreprograma}}
                        </div>
                        <div class="form-group">
                            {{form.tiempo.label_tag}}
                            {{form.tiempo}}
                            {{form.errors.tiempo}}
                        </div>

                        <hr class="mb-2">
                        <div class="col">
                            
                            <input name="programaform" type="submit" value="Editar programa" class="btn btn-success float-right">
                        </div>
                    </form>
                </div>

            </div>
            
        </div>
        
    </div>
</section>
{% endblock %}

ori/templates/editar_timesheet.html
{% extends "base.html" %}
{% block tittle %}
Ori | Editar timesheet {{timesheet.id}}
{% endblock %}

{% block active_module_timesheet%}
active
{% endblock %}

{% block open_timesheet%}-open{% endblock %}

{% block active_timesheets %}
active
{% endblock %}

{% block titulo_main %}
Editar timesheet <b>{{timesheet.id}}</b>
{% endblock %}

{% block path_main %}
<li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
<li class="breadcrumb-item active">editar_timesheet/{{timesheet.id}}</li>
{% endblock %}

{% block main %}
<section class="content">

    <div class="row">
        <div class="col-md-6">
            <div class="card card-purple">
                <div class="card-header">
                    <h3 class="card-title">Edición de la timesheet <b>{{timesheet.id}}</b></h3>
                </div>
                <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="form-group">
                            {{form.tipo.label_tag}}
                            {{form.tipo}}
                            {{form.errors.tipo}}
                        </div>
                        <div class="form-group">
                            {{form.rol.label_tag}}
                            {{form.rol}}
                            {{form.errors.rol}}
                        </div>
                        <div class="form-group">
                            {{form.periodo.label_tag}}
                            <select select name="periodo" class="form-control" required="" id="id_periodo">
                                <option value="" selected="">---------</option>
                                {%for periodo in periodosenproyectoelparticipante%}
                                <option value="{{periodo.id}}">Proyecto (al que pertenece el periodo) =
                                    {{periodo.proyecto.nombreproyecto}} , Número de periodo = {{periodo.num_periodo}}
                                </option>
                                {%endfor%}
                            </select>
                            {{form.errors.periodo}}
                        </div>
                        <div class="form-group">
                            {{form.intellectual_output.label_tag}}
                            {{form.intellectual_output}}
                            {{form.errors.intellectual_output}}
                        </div>
                        <div class="form-group">
                            {{form.num_horas.label_tag}}
                            {{form.num_horas}}
                            {{form.errors.num_horas}}
                        </div>
                    
                        <hr class="mb-2">
                        <div class="col">
                            <a href="{% url 'timesheet' %}" class="btn btn-secondary">Cancel</a>
                            <input name="timesheetform" type="submit" value="Editar {{proyecto.nombreproyecto}}"
                                class="btn btn-success float-right">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Participante y Proyecto</h3>
                </div>
                <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">

                        <div class="form-group">
                            {{form1.participanteproyectos.label_tag}}
                            <select name="participanteproyectos" class="form-control" required=""
                                id="id_participanteproyectos">
                                <option value="" selected="">---------</option>
                                {%for proyectopa in proyectoparti%}
                                <option value="{{proyectopa.id}}">{{proyectopa}}</option>
                                {%endfor%}
                            </select>
                            {{form1.errors.participanteproyectos}}
                        </div>

                        <div class="form-group">
                            {{form1.timesheet.label_tag}}
                            <select name="timesheet" class="form-control" required="" id="id_timesheet" readonly>
                                <option selected="" value="{{timesheet.id}}">{{timesheet.id}} </option>
                            </select>
                            {{form1.errors.timesheet}}
                        </div>

                        <hr class="mb-2">
                        <div class="col">
                            <a href="{% url 'timesheet' %}" class="btn btn-secondary">Cancel</a>
                            <input name="editarparticipanteproyecto" type="submit" value="Editar participante proyecto"
                                class="btn btn-success float-right">
                        </div>
                    </div>
                </form>
            </div>

            <div class="card card-indigo">
                <div class="card-header">
                    <h3 class="card-title">Tareas</h3>
                </div>
                <div class="card-body">
                    <form method="POST" class="post-form" novalidate enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">

                            <div class="form-group">
                                {{form2.nombretarea.label_tag}}
                                {{form2.nombretarea}}
                                {{form2.errors.nombretarea}}
                            </div>
                            <div class="form-group">
                                {{form2.descripcion.label_tag}}
                                {{form2.descripcion}}
                                {{form2.errors.descripcion}}
                            </div>
                            <div class="form-group">
                                {{form2.dia.label_tag}}
                                {{form2.dia}}
                                {{form2.errors.dia}}
                            </div>
                            <div class="form-group">
                                {{form2.lugar.label_tag}}
                                {{form2.lugar}}
                                {{form2.errors.lugar}}
                            </div>
                            <div class="form-group">
                                {{form2.timesheet.label_tag}}
                                <select name="timesheet" class="form-control" required="" id="id_timesheet" readonly>
                                    <option value={{timesheet.id}} selected="">{{timesheet.id}}</option>
                                </select>
                                {{form2.errors.timesheet}}
                            </div>

                        </div>
                        <hr class="mb-2">
                        <div class="col">
                            <a href="{% url 'timesheet' %}" class="btn btn-secondary">Cancel</a>
                            <input name="agregatareaatimesheet" type="submit" value="Agregar tarea"
                                class="btn btn-success float-right">
                        </div>
                    </form>

                    {% if tareas %}
                    <hr class="mb-2">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Nombre tarea</th>
                                <th>Día</th>
                                <th>Lugar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for tarea in tareas%}
                            <tr data-widget="expandable-table" aria-expanded="false">
                                <td>{{tarea.nombretarea|striptags|title}}</td>
                                <td>{{tarea.dia|striptags|title}}</td>
                                <td>{{tarea.lugar|striptags|title}}</td>
                                <td class="text-right py-0 align-middle">
                                    <div class="btn-group btn-group-sm">
                                        <a title="Eliminar tarea de la timesheet" href="/borrar_tarea/{{tarea.id}}"
                                            class="btn btn-danger"
                                            onClick="return confirm('¿Seguro que quieres borrar la tarea {{tarea.nombretarea}}?');"><i
                                                class="fas fa-trash"></i></a>
                                    </div>
                                </td>
                            </tr>
                            
                            <tr class="expandable-body d-none">
                                <td colspan="5">
                                    <p style="display: none;">
                                        <b>Descripción:</b> {{tarea.descripcion}}
                                    </p>
                                </td>
                                
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    {% endif %}


                </div>



            </div>
        </div>

    </div>
    </div>
</section>

{% endblock %}